### ISSUE TITLE
[BUG] Projects: little scrollbar

### ISSUE THREAD

**Issue by SeppeM8** [SELab-2/OSOC-3#567] opened 2022-05-21 18:50 UTC
![image](https://user-images.githubusercontent.com/57944475/169665399-c189778b-ddce-41f8-94a8-a733c2efed69.png)

**Comment by Tiebe-Vercoutter** [comment] 2022-05-21 19:45
Is this fixed in #569 ? I cant reproduce it and there is no **overflow: scroll** left.

**Closed** 2022-05-22 11:09 UTC
Labels: bug, frontend, quick fix
